// action types
const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR';
const OPEN_INGREDIENT_DETAILS = 'OPEN_INGREDIENT_DETAILS';
const OPEN_ORDER_DETAILS = 'OPEN_ORDER_DETAILS';
const CLOSE_MODAL = 'CLOSE_MODAL';
const ADD_INGREDIENT = 'ADD_INGREDIENT';
const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
const UPDATE_COUNTER = 'UPDATE_COUNTER';
const SORT_INGREDIENTS = 'SORT_INGREDIENTS';

// other
const baseUrl = 'https://norma.nomoreparties.space';

export {
  GET_INGREDIENTS_REQUEST,
  GET_INGREDIENTS_SUCCESS,
  GET_INGREDIENTS_ERROR,
  OPEN_INGREDIENT_DETAILS,
  OPEN_ORDER_DETAILS,
  CLOSE_MODAL,
  ADD_INGREDIENT,
  DELETE_INGREDIENT,
  UPDATE_COUNTER,
  SORT_INGREDIENTS,
  baseUrl
};