// action types
const GET_INGREDIENTS = 'GET_INGREDIENTS';
const OPEN_INGREDIENT_DETAILS = 'OPEN_INGREDIENT_DETAILS';
const OPEN_ORDER_DETAILS = 'OPEN_ORDER_DETAILS';
const CLOSE_MODAL = 'CLOSE_MODAL';
const ADD_INGREDIENT = 'ADD_INGREDIENT';
const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
const UPDATE_COUNTER = 'UPDATE_COUNTER';

// other
const baseUrl = 'https://norma.nomoreparties.space';

export {
  GET_INGREDIENTS,
  OPEN_INGREDIENT_DETAILS,
  OPEN_ORDER_DETAILS,
  CLOSE_MODAL,
  ADD_INGREDIENT,
  DELETE_INGREDIENT,
  UPDATE_COUNTER,
  baseUrl
};