// action types
const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR';
const OPEN_INGREDIENT_DETAILS = 'OPEN_INGREDIENT_DETAILS';
const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
const SEND_ORDER_ERROR = 'SEND_ORDER_ERROR';
const OPEN_ORDER_DETAILS = 'OPEN_ORDER_DETAILS';
const CLOSE_MODAL = 'CLOSE_MODAL';
const ADD_INGREDIENT = 'ADD_INGREDIENT';
const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
const UPDATE_COUNTER = 'UPDATE_COUNTER';
const SORT_INGREDIENTS = 'SORT_INGREDIENTS';
const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
const AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST';
const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';
const SET_USER_DATA = 'SET_USER_DATA';
const UPDATE_TOKEN_REQUEST = 'UPDATE_TOKEN_REQUEST';
const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
const UPDATE_TOKEN_ERROR = 'UPDATE_TOKEN_ERROR';
const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_ERROR = 'LOGOUT_ERROR';
const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';
const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
const UPDATE_USER_DATA_ERROR = 'UPDATE_USER_DATA_ERROR';

// other
const baseUrl = 'https://norma.nomoreparties.space';

export {
  baseUrl,
  GET_INGREDIENTS_REQUEST,
  GET_INGREDIENTS_SUCCESS,
  GET_INGREDIENTS_ERROR,
  SEND_ORDER_REQUEST,
  SEND_ORDER_SUCCESS,
  SEND_ORDER_ERROR,
  OPEN_INGREDIENT_DETAILS,
  OPEN_ORDER_DETAILS,
  CLOSE_MODAL,
  ADD_INGREDIENT,
  DELETE_INGREDIENT,
  UPDATE_COUNTER,
  SORT_INGREDIENTS,
  CHANGE_PASSWORD_REQUEST,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_ERROR,
  RESET_PASSWORD_REQUEST,
  RESET_PASSWORD_SUCCESS,
  RESET_PASSWORD_ERROR,
  REGISTRATION_REQUEST,
  REGISTRATION_SUCCESS,
  REGISTRATION_ERROR,
  AUTHORIZATION_REQUEST,
  AUTHORIZATION_SUCCESS,
  AUTHORIZATION_ERROR,
  SET_USER_DATA,
  UPDATE_TOKEN_REQUEST,
  UPDATE_TOKEN_SUCCESS,
  UPDATE_TOKEN_ERROR,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_ERROR,
  GET_USER_DATA_REQUEST,
  GET_USER_DATA_SUCCESS,
  GET_USER_DATA_ERROR,
  UPDATE_USER_DATA_REQUEST,
  UPDATE_USER_DATA_SUCCESS,
  UPDATE_USER_DATA_ERROR
};